### PR TITLE
Remove some remaining authentication remnants

### PR DESCRIPTION
**Pull request by harrisj**
When they first created this app, they used a Flask skeleton app which had support for user login and the like. This API has no user logins (only a single shared token used by the API frontend proxy), so I removed most of that in PR #121

But there were some references to setting a SECRET in the docs and in the environment variable, so need to clean those up.

Also, removing http_auth which was only there for protecting the Swagger.json page before we started ATO process.

### CODE REVIEW

**Comment by cacraig** [comment]
@harrisj  - The tests seem to have failed on this one.  

E           RuntimeError: The Flask-DebugToolbar requires the 'SECRET_KEY' config var to be set

**Comment by harrisj** [comment]
Yep, I decided to go ahead and yank out some of the debugging bits (like the Flask Toolbar) and the asset pipelines and templating that were being used only by our error pages.

**Comment by harrisj** [comment]
Tests now pass. This is good for review again @cacraig

**Comment by cacraig** [comment]
Merging!

**Pull request merged**
