### PR TITLE
WIP: Create reta_annual_offense_agency_summary table

### LINKED ISSUE #448: Create new denormalized table for agency annual counts
This will be a similar approach to reta_month_offense_subcat_summary

### PR DESCRIPTION
**Pull request by harrisj**
Work in progress. **DO NOT MERGE YET**

Fixes #448

### CODE REVIEW

**Comment by harrisj** [comment]
Any comments on this? Are there some fields I should add?

**Comment by cacraig** [comment]
@harrisj  - I added the partition triggers to functions.sql. One thing, I think we should morph the "year" field into a date field. That will allow us to utilize date range utilities, and such.

**Comment by cacraig** [comment]
@harrisj  - This is all live, and good to be merged in. Can you take a look at it + merge it (since I've done all the recent stuff to this pr)

**Comment by harrisj** [comment]
LGTM. Next we can work on the API endpoint!

**Pull request merged**
