### PR TITLE
Added Denormalization scripts + Materialized view scripts - DO NOT MERGE

### PR DESCRIPTION
**Pull request by cacraig**
This contains big Denormalization scripts for Offender/Victims. It also creates materialized views for the desired groupings (by year).

Additionally. When this is merged - The API will use the full DB (finally).

DO NOT MERGE YET

### CODE REVIEW

**Comment by harrisj** [comment]
One tweak, can name the tables and views with a `cde_` prefix? I think this will make it easier to distinguish our tables and views from the FBI-provided ones

**Comment by cacraig** [comment]
@harrisj That is actually going to be a bigger issue than it seems. These tables are already live, and have partitions + dependent materialized views that would need to be refreshed.  We would probably have to rebuild the partitions + views.

**Comment by harrisj** [comment]
Fair enough. Never mind me!

**Comment by cacraig** [comment]
No longer needed. See #296

**Pull request closed without merging**
