### PR TITLE
Scraping script for BJS.gov, and data dumps.

### PR DESCRIPTION
**Pull request by cacraig**
Initial script to scrape data from bjs.gov, and the output files from it.

### CODE REVIEW

**Comment by cacraig** [comment]
Hey @catherinedevlin , can you look over this? Thanks!

**Comment by jeremiak** [comment]
This is awesome, I was trying to clean this data up myself but having it scraped is way better! The `state.json` file is great, and useful for some super quick plotting but it uses absolute counts, and I think we'll need the population of each state in each year to do some controlling for population. Is that something we can add from the BJS scrape?

**Comment by cacraig** [comment]
Yep! @jeremiak. Not sure why I left population out. I'll re-run the script, but leave population in. I'm also going to switch the nesting of the agencies.json file to be state -> agency -> year. Might be a little easier to deal with.

**Comment by cacraig** [comment]
Hey @jeremiak , the data is updated, and includes populations now.

**Pull request merged**
