### PR TITLE
Add participating population for NIBRS to participation_rate

### LINKED ISSUE #557: Add nibrs_participating_population to participation_rates?
We might need this as a better measure to decide whether to display NIBRS for a given state, since looking at total agencies might be distorted for smaller states (ie, for DC's 5 agencies, 20% (or 1) participate in NIBRS)

### PR DESCRIPTION
**Pull request by harrisj**
Fixes #557

### CODE REVIEW

**Comment by cacraig** [comment]
@harrisj  - I'm good for merging this - however, should we be concerned about the merge conflict on the sql file (given the replacement proposed?).

**Comment by harrisj** [comment]
I'll rebase if you want

**Comment by harrisj** [comment]
Rebased and ready to be merged

**Comment by cacraig** [comment]
Merging! LGTM.

**Pull request merged**
