### PR TITLE
Model entities

### PR DESCRIPTION
**Pull request by cacraig**
So this is a big one. These are the auto-generated models from the data dump from the UCR.

- Merged in auto generated models, and got rid of inferior models.
- Decomposed models into logical bits.
- Reworked application structure.

### CODE REVIEW

**Comment by cacraig** [comment]
@catherinedevlin  - Hey Catherine. I reworked the application structure to perhaps be easier to manage. I also decomposed the models into different apps.

**Comment by catherinedevlin** [comment]
Wow.  You work fast.

One thing I don't understand is when to split models into separate apps.  Our endpoints will need to reach across different groups of models pretty much constantly - for instance, the serializer for an incident will pull from NIBRS models, but also (eventually) from CT, HT, and SHR models.  Will having those in separate apps make that harder?

**Comment by cacraig** [comment]
My thinking was that we could create an entity called "Incident" for example, and have it be a composition of the various flavors of incidents. 

```python  

class Incident(object):
    def __init__(self):
        ct = CtIncident()
        hc = HcIncident()
        ht = HtIncident()
    def getIncidents():
        return ht.getIncidents() + hc.getIncidents() + ct.getIncidents()

```

**Comment by catherinedevlin** [comment]
OK, thanks for that explanation!

**Pull request merged**
