### PR TITLE
Loading the revised cargo theft data

### LINKED ISSUE #535: Load corrected cargo theft incidents

### PR DESCRIPTION
**Pull request by harrisj**
Fixes #535 

This is already in production and there are no code changes. The question is if you want an API endpoint for downloading ct incidents...

### CODE REVIEW

**Comment by cacraig** [comment]
@harrisj - We already have one. https://github.com/18F/crime-data-api/blob/master/dba/after_load/mat-views/cargo-theft.sql

**Comment by harrisj** [comment]
Yep, I refreshed the view already! But do you need to rerun a query ro get CSV for the downloads page?

**Comment by cacraig** [comment]
@harrisj  - What CSV download are you referring to? I'm not sure we have a bulk download for cargo theft.

**Comment by jeremiak** [comment]
There is working download at http://s3-us-gov-west-1.amazonaws.com/cg-d3f0433b-a53e-4934-8b94-c678aa2cbaf3/cargo_theft.csv. Is that not updated/valid anymore?

**Comment by harrisj** [comment]
Yes, they had me load revised cargo theft data that reduced the total number of incidents by a factor of 5, but it also includes 2015. I have already updated all the database tables, but I think we need to save a new version of that file.

**Comment by cacraig** [comment]
Huh, I must of blanked out on that one. However, if we are providing API access, why are we providing a bulk file? These bulk files were for data we didn't provide API's for, right? @jeremiak @harrisj

**Comment by cacraig** [comment]
Anywho - the file has been updated  - gonna merge this.

**Comment by jeremiak** [comment]
Good question @cacraig! I think there is value in having both, but perhaps we should make that download button utilize the API to generate the CSV (`output=csv`) instead of requiring it also added to S3?

I think there is value in having a CSV because flat files are easier to get started doing analysis.

**Comment by LarryBafundo** [comment]
yes, our intent is for the API to provide access to as much of the data as possible, but in cases where we have gaps, like the bulk NIBRS state downloads, we offer a pre-prepared download. in cases where we do provide access to the data via the API, you can still make a case for a bulk download because not all consumers of the data will be users of the API.

**Pull request merged**
