### PR TITLE
Materialized views for participation rates

### LINKED ISSUE #310: View UCR participation rate by state
As a user, I want to understand how many agencies within a state participate in the UCR program when reviewing data for that state.

### PR DESCRIPTION
**Pull request by harrisj**
Fixes #310

This will allow us to add participation rates to the `/geo` endpoint when done

### CODE REVIEW

**Comment by jeremiak** [comment]
This is a nitpick, and I noticed it from the [comment in 290](https://github.com/18F/crime-data-api/issues/290#issuecomment-276987728), but can we change the `data_year` key in the JSON response to just be `year`?

**Comment by harrisj** [comment]
Sure...

**Comment by jeremiak** [comment]
For the sake of consistency since I believe it is just `year` in every other response

**Comment by cacraig** [comment]
GTG!

**Pull request merged**
