### PR TITLE
Create an offense-grouped version of agency_sums table

### LINKED ISSUE #518: update agency offense endpoint
* use sub-offense table and group results (reports, cleared, actuals) by the offense that's supplied

i.e., /offenses/ORI_ID?offense=SOMETHING returns

```
{year: 2000, offense: SOMETHING, reported: 10, actual: 8, cleared: 5},
{year: 2001, offense: SOMETHING, reported: 12, actual: 9, cleared: 4},
```

cc: @harrisj @cacraig @jeremiak

### PR DESCRIPTION
**Pull request by harrisj**
Fixes #518

This still needs some tests, but it creates an offense-grouped equivalent of the agency_sums_view

### CODE REVIEW

**Comment by harrisj** [comment]
The table is done, but it needs a little documentation for the method

**Comment by harrisj** [comment]
This should be ready to go an I would love a review today

**Comment by harrisj** [comment]
Fixes #492

**Comment by cacraig** [comment]
This looks okay to me -  Merging.

**Pull request merged**
