### PR TITLE
Remove the aggregate_many param from Swagger

### LINKED ISSUE #505: What does the "aggregate_many" parameter mean?
There is no description for the `aggregate_many` parameter in some of the API endpoints, though it is a somewhat vague variable name. Can we define it in the API documentation?

For reference, I am specifically referring to the `/offenders/count/national/{variable}` endpoint.

### PR DESCRIPTION
**Pull request by harrisj**
It doesn't appear to be supported anymore.

Fixes #505

### CODE REVIEW

**Comment by harrisj** [comment]
Added some things so this will now fix #509 too

**Comment by harrisj** [comment]
Okay, I broke the build so don't merge this yet

**Comment by harrisj** [comment]
Okay, I fixed the build so it can be merged!

**Comment by cacraig** [comment]
LGTM!

**Pull request merged**
