### PR TITLE
Fix qualified field names

### PR DESCRIPTION
**Pull request by catherinedevlin**
Fixes several bugs in the `victim.`, `offender.`, `arrestee.` filters.

*However*, it also introduces (or at least reveals) another bug with pagination numbers and overall record counts!  (Thus the tests marked xfail.)  I'll fix that bug later today, but it doesn't cause false (just incomplete) results, so I wanted to get this code deployed for folks to develop against.

### CODE REVIEW

**Comment by cacraig** [comment]
Hey @catherinedevlin - I did /incidents/?ori=MA0051 - and it returns no results. /incidents/?ori=MA0051100 returns results. It seems like with ILIKE implementation we would want results here, right?

**Comment by catherinedevlin** [comment]
Hmm...

I was only temporarily using ILIKE to get case-insensitivity, but wasn't including wildcards even then.  Now I'm doing case-insensitively differently so ILIKE is out.

I don't want to ILIKE by default, for performance reasons and b/c it can be confusing.  However, supporting a `~` operation that would use ILIKE could be awesome!  Should we make a ticket for that?

Somebody stop me before I suggest supporting regex searching.

**Comment by cacraig** [comment]
@catherinedevlin Yeah, that sounds reasonable. I think it's also a fairly small use-case as well. I submitted an issue for it.

**Comment by cacraig** [comment]
Looks good. Merging!

**Pull request merged**
