### PR TITLE
Bring back arson endpoint

### LINKED ISSUE #552: Create special arson table for national/state arson table
Right now, the only CDE use of the /codes/ endpoint and reta_month_offense_subcat_summary table is for arson counts as the state and national level. I think we should move this usage to a separate endpoint and deprecate the /counts/ API since this table is huge and takes forever to generate and would slow down a load of 2015 or later data.

### PR DESCRIPTION
**Pull request by harrisj**
Fixes #552.

I still need to build the table in production, but that shouldn't take too long

### CODE REVIEW

**Comment by cacraig** [comment]
@harrisj  - I can merge, looks good - Is the DB ready for this?

**Comment by harrisj** [comment]
Looks like the DB is ready, but I need to fix a merge conflict

**Comment by harrisj** [comment]
Meege conflict fixed

**Comment by cacraig** [comment]
GTG. Merging.

**Pull request merged**
