### PR TITLE
Reduce size of test db slice

### LINKED ISSUE #564: Make test DB slice much smaller
It's huge and unwieldy. My suggestion is to just limit to Rhode Island 2014 data and such and fix any tests to use it. Will get to it here and there.

### PR DESCRIPTION
**Pull request by harrisj**
Fixes #564 

This removes much of the data in the test slice that isn't about Rhode Island in 2014, so I hope you like coffee milk and not as many agencies.

The advantage: shrinking the test DB slice from 90MB to 9MB

Still working on this in my spare time: need to fix Cargo Theft, but it is close. Note that this also involved making a few fixes to the materialized view SQL I'd appreciate some oversight on

### CODE REVIEW

**Comment by cacraig** [comment]
@harrisj  I'd like to get this merged in so I can apply the changes required for https://github.com/18F/crime-data-api/pull/573 to the dump file. So let me know when this is gtg. Otherwise it looks good to me.

**Comment by harrisj** [comment]
Should be GTG, but looks like I need to rebase. Again

**Comment by harrisj** [comment]
This has been rebased and can be merged

**Comment by cacraig** [comment]
I'm into it! Merging!

**Pull request merged**
