### PR TITLE
Remove tests for users and roles

### LINKED ISSUE #117: Remove Users/Roles functionality from Flask structure?
It looks like the Flask skeleton we setup the app with included some functionality for users and roles, including DB structures, unit tests, blueprints, etc. These are currently not used by the app (it's an API of course), so I think it would be a good idea to remove them, lest they cause some confusion down the road.

### PR DESCRIPTION
**Pull request by harrisj**
Fixes #117 

These were part of the initial Flask scaffolding and are not used, so best to not keep tests that slow down everything and could break. There are still a few other places to clean up this code if we want to continue removing code that is not actually used (I recommend doing that):

- [x] The User and Role model
- [x] The blueprints for user and public (this would mean we need a new homepage)
- [x] The login_manager

What do you think?

### CODE REVIEW

**Comment by catherinedevlin** [comment]
This looks great, thank you.

I think we should also delete the code you mention.  Should I merge this now, or do you want to commit those deletions to this same PR first?

**Comment by harrisj** [comment]
I can add them to this PR

**Comment by harrisj** [comment]
So I have removed the User model and factories and also the blueprints and templates for the User and the generic Public screen from the Flask starter. This means that the site 500s if you go to the / page right now (before it rendered a generic page about it being a Flask project with bootstrap and such). I think this is acceptable for now, but I wonder if we should add a screen or such down the road. We would likely have to password-protect access to the screen before we get an ATO though.

**Comment by cacraig** [comment]
If we can fix the conflicts on this one, I'll get it merged in quickly,  @harrisj .

**Comment by cacraig** [comment]
GTG.

**Pull request merged**
