### PR TITLE
CDE States Table

### LINKED ISSUE #515: Create cde_states table
As part of the work on #512, I created a denormalized `cde_counties` table instead. This allowed me to clean up the hackish code for CdeRefCounty. It might make sense to make a similar denormalized table for the CdeRefState model that pulls into a single table the data queried by the CdeRefState model

### PR DESCRIPTION
**Pull request by harrisj**
Fixes #515 

This has not been applied to production yet and I really don't want to mess with the DB today, but I am putting this here.

### CODE REVIEW

**Comment by harrisj** [comment]
This has been rebased and can be merged

**Comment by harrisj** [comment]
Another rebase

**Comment by harrisj** [comment]
Do you think we could merge this today?

**Comment by cacraig** [comment]
@harrisj  - Looks good to me! Merging.

**Pull request merged**
