### PR TITLE
Add county information to cde_agencies table

### LINKED ISSUE #512: Add county information to the cde_agencies table
We want to add the primary county for a given agency to the cde_agencies table. This involves a few little considerations:

1. Agencies may be in multiple counties, but let's pick the one they are mainly in to display (will have to see if some agencies are evenly split, but I assume most are usually in one county mostly)
2. County names in `ref_county` are capitalized, and there are some cases where we can't just titleize from DEKALB to Dekalb (it's actually DeKalb)
3. We currently have a county view for data that involves a bunch of inefficient queries and I've been meaning to fix.
4. Related, there is no easy means for a FIPS -> County search, since the FBI database splits FIPS into state and county tables.

So, I'm going to propose handling this in several steps:
1. Create a `cde_counties` table that has printable names for the counties, full five-character FIPS codes and other useful fields from the `CdeRefCounty` model.
2. Make CdeRefCounty use this as its base table (should be an easy fix)
3. Associate in the primary county and primary county FIPS into the cde_agencies table

### PR DESCRIPTION
**Pull request by harrisj**
Fixes #512 

This still needs some tests and will require a few tables to be regenerated on the database, but it's almost there.

### CODE REVIEW

**Comment by harrisj** [comment]
The data is now on the database so this is ready to go for review

**Comment by harrisj** [comment]
Actually, this can't be merged yet, since I need to rebase it off #503 which I would like to get merged first

**Comment by harrisj** [comment]
Okay, this is ready to be merged.

**Comment by harrisj** [comment]
This is ready to be reviewed. Had to merge because rebase failed...

**Comment by harrisj** [comment]
Fixes #512

**Comment by harrisj** [comment]
Rebased, so I'd like to see if we could get this merged today.

**Comment by cacraig** [comment]
Looks Good! Thanks! Merging ~

**Pull request merged**
