### PR TITLE
[WIP - Do not commit] Initial commit - NIBRS Agency API

### PR DESCRIPTION
**Pull request by cacraig**
- Added agency aggregations to Mat views
- Compacted/re-orged Materialized views SQL 
- Modified APIs to give null for missing fields

### CODE REVIEW

**Comment by cacraig** [comment]
@harrisj  - When you get a chance, can you take a look at this? - I needed to disable the swagger doc verification for the tests, and some parts of the unit tests because of how it handles null fields. Since null is now returned when a data point is missing/0.

**Comment by harrisj** [comment]
Okay, I brought back the Swagger tests, but the test_cdemodels tests run really slowly on my machine for some reason...

**Comment by cacraig** [comment]
Thanks @harrisj  - The slowness is caused by the JOINING on some pretty big tables - which would be compounded on production. I modified the queries to scan our denormalized/partitioned tables (only one year) instead. We can further tweak it (if necessary) by creating some views to join on that have these distinct values.

**Comment by cacraig** [comment]
Assuming this passes tests - this is done, and ready for another review. The DB changes are live as well. @harrisj

**Comment by harrisj** [comment]
I would ultimately like to fix some of those tests you had to weaken, but this is generally looking good so I don't want to hold things up too much longer, especially since there is high need for this in the sprint. Is this ready to be merged?

**Comment by cacraig** [comment]
I'd like to get this deployed, so I can evaluate performance issues against the main DB - I'll submit a followup PR with better tests/docs + fixes for performance problems that may arise. Anywho, it is ready to go @harrisj - Thanks.

**Comment by harrisj** [comment]
I can help with the tests later. Merging.

**Pull request merged**
